### PR TITLE
Change Responsive Provider proptypes

### LINKED ISSUE #7: Invalid props in ResponsiveProvider
## Issue Report

There are some problems related to proptypes.

## Expected Behavior

- `breakpoints` should not trigger a warning.
- `mediaQueries` and `breakpointsMax` should have clear shapes.

## Actual Behavior

- `breakpoints` is giving an invalid prop warning.
- `mediaQueries` and `breakpointsMax` have `PropTypes.any`.

## Steps to Reproduce the Issue

You can test this with `yarn test`

### PR DESCRIPTION
**Pull request by nersoh**
# PR Details

## Description
Add more specific proptypes to `ResponsiveProvider` component

## Related Issue
Closes #7 

## Motivation and Context
Remove warnings when passing props

## How Has This Been Tested
Running tests suite

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](../docs/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

File: src/ResponsiveProvider.js [hunk 1]
```diff
@@ -151,16 +151,28 @@ ResponsiveProvider.propTypes = {
...
-            mediaQuery: PropTypes.string,
-            mediaType: PropTypes.string,
-        })
-    ),
-    // eslint-disable-next-line react/forbid-prop-types
-    mediaQueries: PropTypes.any,
-    // eslint-disable-next-line react/forbid-prop-types
-    breakpointsMax: PropTypes.any,
+    breakpoints: PropTypes.shape({
+        xs: PropTypes.string,
```
Comment (SoaresMG) [inline src/ResponsiveProvider.js:155]: Would it be possible to have a single shape and re-use it where it's needed?

Comment (nersoh) [reply src/ResponsiveProvider.js]: Sure.

**Comment by SoaresMG** [comment]
Should this be a `fix` instead of a `chore`? Since it affects the client

**Comment by nersoh** [comment]
> Should this be a `fix` instead of a `chore`? Since it affects the client

It affects the client by showing `warnings`, but not preventing from functioning properly. Also, I saw many examples of "warning fix" taken as `chore`. But what you guys find more appropriate, we can apply 😉

**Comment by SoaresMG** [comment]
> > Should this be a `fix` instead of a `chore`? Since it affects the client
> 
> It affects the client by showing `warnings`, but not preventing from functioning properly. Also, I saw many examples of "warning fix" taken as `chore`. But what you guys find more appropriate, we can apply 😉

By default semantic-release doesn't care about "chore" since normally it's about tooling, documentation, and similar.

Anything else than `fix` or `feat` will not end up on the client's bundle.

These are the default values for [semantic-release conventionalcommits](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md)

Only `feat` and `fix` create a new release.

Perhaps we could discuss if we need something to extend this?
@themariamarques @dinospereira @sofiacteixeira

File: src/ResponsiveProvider.js [hunk 2]
```diff
@@ -139,6 +139,14 @@ const ResponsiveProvider = ({
     );
 };
 
+const breakpointsPropTypes = {
```
Comment (stephan-noel) [inline src/ResponsiveProvider.js:142]: Are all of these keys always expected, and if so, are they always these exact keys?

If this is true, do you think we should update the `initialMediaType` to use `oneOf` and then these keys instead of `PropTypes.string`, and also update defaultOrientation to use` oneOf(["portrait", "landscape"])` ?  Just since you're already changing the PropTypes anyway.

Comment (nersoh) [reply src/ResponsiveProvider.js:142]: Great points. I'll change that.

**Comment by nersoh** [comment]
Added changes proposed by @stephan-noel. Please, check if they make sense @SoaresMG @sofiacteixeira @joaopedrodcf

File: src/ResponsiveProvider.js (hunk 2 above)
Comment (stephan-noel) [reply src/ResponsiveProvider.js:142]: Nice, thanks!

**Comment by SoaresMG** [comment]
Everything seems fine but we should release it as a fix so it triggers the pipeline, we will talk about making "chore" released as well in the future

**Review by joaopedrodcf — APPROVED** [review]

**Review by SoaresMG — APPROVED** [review]

**Review by dinospereira — APPROVED** [review]
